export type Language = 'en' | 'es' | 'it' | 'fr' | 'pt';

interface ConfidenLang {
  back: string;
  subtitle: string;
  title: string;
  titleHighlight: string;
  paragraphs: string[];
  ctaTitle: string;
  ctaTitleHighlight: string;
  ctaDesc: string;
  ctaBtn: string;
}

export const confidenTranslations: Record<Language, ConfidenLang> = {
  en: {
    back: "Back",
    subtitle: "Legal Policy",
    title: "Privacy Policy",
    titleHighlight: "& Terms of Use",
    paragraphs: [
      "This Privacy Policy and Terms of Use govern the access, navigation, and use of this website, as well as the processing of information and personal data provided by users, prospective clients, clients, and third parties who interact with our digital or professional services. Accessing, using, or communicating through this website constitutes the free, express, and informed acceptance of the provisions contained herein.",
      "Our firm recognizes the right to privacy, confidentiality, and the protection of personal data as essential principles in the professional practice of law and in the provision of legal services. Accordingly, all information received shall be processed in accordance with the laws of the Republic of Panama, particularly under the framework established by Law 81 of 2019 on Personal Data Protection and its regulations under Executive Decree 285 of 2021, as well as in accordance with principles recognized under international standards on personal data protection and privacy.",
      "The information provided through forms, emails, digital communications, or any other contact method may include personal, corporate, financial, patrimonial, or documentary identification data. The user declares and warrants that all information provided is truthful, complete, updated, and lawfully supplied, assuming full responsibility for any falsehood, omission, or inaccuracy that may generate legal consequences or affect the proper evaluation of their matter or inquiry. All information collected shall be used exclusively for legitimate purposes, including preliminary evaluation of legal inquiries, legal feasibility analysis, preparation of professional proposals, compliance verification, conflict of interest prevention, due diligence processes, regulatory compliance, internal management, and, where applicable, the proper provision of professional legal services.",
      "The submission of information through this website, its forms, or any digital means of contact shall under no circumstances constitute the automatic creation of an attorney-client relationship, mandate, legal representation, or professional relationship of any kind. Any professional relationship shall require the firm's express, formal, and verifiable acceptance, as well as the formal execution of the corresponding legal instruments. The mere receipt of an inquiry, communication, or documentation shall not create any obligation to respond, accept a matter, or undertake representation. The firm reserves the absolute and discretionary right to accept, reject, suspend, or terminate any inquiry, evaluation process, or professional relationship, without any obligation to justify its decision, particularly where conflicts of interest, insufficient documentation, inconsistencies in the information provided, regulatory risks, reputational risks, or any circumstance compromising the firm's professional independence, regulatory compliance, or ethical integrity may arise. Any initial evaluation or preliminary communication made by the firm shall be considered purely informative, preliminary, and non-binding, and shall not be interpreted as a definitive legal opinion, formal legal strategy, guarantee of representation, or commitment to any result. No information contained on this website constitutes individualized legal advice nor substitutes a formal professional legal consultation.",
      "The firm does not guarantee specific outcomes, favorable resolutions, economic benefits, administrative authorizations, judicial decisions, regulatory approvals, or any concrete result arising from the provision of professional services, as all legal actions depend on external factors, judicial discretion, administrative actions, evidentiary elements, and particular circumstances beyond professional control. The user acknowledges that any decision made based on general information contained on this website or on preliminary communications shall be undertaken at their sole responsibility. Consequently, the firm shall not assume liability for decisions, acts, omissions, investments, contracts, or patrimonial movements executed without the formal engagement of professional legal counsel. The firm implements reasonable technical, administrative, and organizational measures to protect the information received, including internal security protocols, access controls, document safeguarding, and digital protection mechanisms. However, the user acknowledges that no technological system, digital platform, or computer network is entirely infallible, and therefore the firm does not guarantee absolute security against force majeure events, cyberattacks, unlawful access by third parties, or technological vulnerabilities beyond reasonable control.",
      "All information received may be subject to internal due diligence processes, documentary validation, identity verification, analysis of patrimonial legitimacy, source of funds, corporate structuring, and regulatory compliance, in accordance with national and international legal, ethical, and regulatory standards. Refusal to cooperate with these processes may constitute sufficient grounds for rejecting or terminating any professional relationship.",
      "The firm expressly reserves the right to refrain from providing professional services, suspend legal actions, or terminate contractual relationships where there are reasonable indications or well-founded suspicions that its services may be used, directly or indirectly, for unlawful activities, money laundering, fraud, unlawful tax evasion, fraudulent legal simulation, improper concealment of assets, corruption, unlawful financing, or any activity contrary to national or international law.",
      "The user expressly declares that they shall not use the firm's legal services for unlawful, fraudulent, or public-order-violating purposes and undertakes to act in accordance with the law and under principles of good faith, transparency, and legality. Any breach of this obligation shall entitle the firm to immediately cease all professional actions, without prejudice to any legal actions that may correspond.",
      "Personal information shall be retained only for the time necessary to fulfill its legitimate purpose, comply with legal, contractual, or regulatory obligations, or exercise and defend legal rights and interests. Thereafter, such information may be deleted, blocked, or anonymized in accordance with applicable law.",
      "Users may exercise their rights of access, rectification, updating, cancellation, or opposition regarding their personal data, in accordance with the procedures established under applicable Panamanian law. This website may use cookies and similar technologies for functional, statistical, security, and navigation experience optimization purposes. Users may manage such settings directly through their browser. The firm may modify, update, or expand this policy at any time when necessary due to legislative, regulatory, technological, or internal policy changes. Any modifications shall become effective upon publication on this website. Any legal relationship arising from the use of this website, its content, communications, or services shall be governed by and construed in accordance with the laws of the Republic of Panama. Any dispute related to the interpretation, enforcement, or application of this policy shall be submitted exclusively to the competent courts of the Republic of Panama, with the express waiver of any other jurisdiction or venue that may otherwise apply.",
    ],
    ctaTitle: "Your privacy",
    ctaTitleHighlight: "is guaranteed.",
    ctaDesc: "Every interaction with Yanguéz Legal Group is conducted under strict confidentiality protocols. We invite you to reach out with complete peace of mind.",
    ctaBtn: "Contact Us Securely",
  },

  es: {
    back: "Volver",
    subtitle: "Política Legal",
    title: "Política de Privacidad",
    titleHighlight: "y Términos de Uso",
    paragraphs: [
      "La presente Política de Privacidad y Términos de Uso rigen el acceso, navegación y uso de este sitio web, así como el tratamiento de la información y datos personales proporcionados por usuarios, clientes potenciales, clientes y terceros que interactúen con nuestros servicios digitales o profesionales. El acceso, uso o comunicación a través de este sitio web constituye la aceptación libre, expresa e informada de las disposiciones aquí contenidas.",
      "Nuestra firma reconoce el derecho a la privacidad, confidencialidad y protección de datos personales como principios esenciales en el ejercicio profesional del derecho y en la prestación de servicios legales. En consecuencia, toda información recibida será tratada conforme a las leyes de la República de Panamá, particularmente bajo el marco establecido por la Ley 81 de 2019 sobre Protección de Datos Personales y su reglamentación mediante el Decreto Ejecutivo 285 de 2021, así como en concordancia con los principios reconocidos en los estándares internacionales de protección de datos personales y privacidad.",
      "La información proporcionada a través de formularios, correos electrónicos, comunicaciones digitales u otro método de contacto podrá incluir datos personales, corporativos, financieros, patrimoniales o de identificación documental. El usuario declara y garantiza que toda la información suministrada es veraz, completa, actualizada y lícitamente proporcionada, asumiendo plena responsabilidad por cualquier falsedad, omisión o inexactitud que pueda generar consecuencias legales o afectar la correcta evaluación de su asunto o consulta. Toda la información recolectada será utilizada exclusivamente para fines legítimos.",
      "La remisión de información a través de este sitio web, sus formularios o cualquier medio digital de contacto no constituirá en ningún caso la creación automática de una relación abogado-cliente, mandato, representación legal o relación profesional de ningún tipo. Toda relación profesional requerirá la aceptación expresa, formal y verificable de la firma, así como la suscripción formal de los instrumentos legales correspondientes. La mera recepción de una consulta, comunicación o documentación no crea obligación alguna de responder, aceptar un asunto o asumir representación. La firma se reserva el derecho absoluto y discrecional de aceptar, rechazar, suspender o dar por terminada cualquier consulta, proceso de evaluación o relación profesional, sin obligación de justificar su decisión.",
      "La firma no garantiza resultados específicos, resoluciones favorables, beneficios económicos, autorizaciones administrativas, decisiones judiciales, aprobaciones regulatorias ni ningún resultado concreto derivado de la prestación de servicios profesionales, toda vez que toda actuación legal depende de factores externos, discrecionalidad judicial, actuaciones administrativas, elementos probatorios y circunstancias particulares ajenas al control profesional. El usuario reconoce que cualquier decisión tomada con base en información general contenida en este sitio o en comunicaciones preliminares será de su exclusiva responsabilidad. La firma implementa medidas técnicas, administrativas y organizacionales razonables para proteger la información recibida. Sin embargo, el usuario reconoce que ningún sistema tecnológico es completamente infalible.",
      "Toda información recibida podrá ser sometida a procesos internos de debida diligencia, validación documental, verificación de identidad, análisis de legitimidad patrimonial, origen de fondos, estructuración corporativa y cumplimiento regulatorio, conforme a los estándares legales, éticos y regulatorios nacionales e internacionales. La negativa a cooperar con estos procesos podrá constituir causa suficiente para rechazar o terminar cualquier relación profesional.",
      "La firma se reserva expresamente el derecho de abstenerse de prestar servicios profesionales, suspender actuaciones legales o dar por terminadas relaciones contractuales cuando existan indicios razonables o sospechas fundadas de que sus servicios puedan ser utilizados, directa o indirectamente, para actividades ilícitas, lavado de activos, fraude, evasión fiscal ilícita, simulación legal fraudulenta, ocultamiento indebido de bienes, corrupción, financiamiento ilícito o cualquier actividad contraria a la legislación nacional o internacional.",
      "El usuario declara expresamente que no utilizará los servicios legales de la firma para fines ilícitos, fraudulentos o contrarios al orden público, y se compromete a actuar conforme a la ley y bajo los principios de buena fe, transparencia y legalidad. Cualquier incumplimiento de esta obligación facultará a la firma para cesar inmediatamente todas las actuaciones profesionales.",
      "La información personal será conservada únicamente por el tiempo necesario para cumplir con su finalidad legítima, dar cumplimiento a obligaciones legales, contractuales o regulatorias, o ejercer y defender derechos e intereses legítimos. Transcurrido dicho período, la información podrá ser eliminada, bloqueada o anonimizada conforme a la ley aplicable.",
      "Los usuarios podrán ejercer sus derechos de acceso, rectificación, actualización, cancelación u oposición respecto de sus datos personales, de conformidad con los procedimientos establecidos en la legislación panameña aplicable. Este sitio web podrá utilizar cookies y tecnologías similares para fines funcionales, estadísticos, de seguridad y optimización de la experiencia de navegación. La firma podrá modificar, actualizar o ampliar esta política en cualquier momento. Toda relación legal derivada del uso de este sitio web se regirá por las leyes de la República de Panamá, y cualquier controversia será sometida exclusivamente a los tribunales competentes de la República de Panamá.",
    ],
    ctaTitle: "Su privacidad",
    ctaTitleHighlight: "está garantizada.",
    ctaDesc: "Cada interacción con Yanguéz Legal Group se lleva a cabo bajo estrictos protocolos de confidencialidad. Le invitamos a comunicarse con total tranquilidad.",
    ctaBtn: "Contáctenos de Forma Segura",
  },

  it: {
    back: "Indietro",
    subtitle: "Politica Legale",
    title: "Informativa sulla Privacy",
    titleHighlight: "e Termini d'Uso",
    paragraphs: [
      "La presente Informativa sulla Privacy e Termini d'Uso disciplinano l'accesso, la navigazione e l'utilizzo di questo sito web, nonché il trattamento delle informazioni e dei dati personali forniti da utenti, potenziali clienti, clienti e terzi che interagiscono con i nostri servizi digitali o professionali. L'accesso, l'utilizzo o la comunicazione tramite questo sito web costituisce l'accettazione libera, espressa e consapevole delle disposizioni qui contenute.",
      "Il nostro studio riconosce il diritto alla privacy, alla riservatezza e alla protezione dei dati personali come principi essenziali nell'esercizio professionale del diritto e nella fornitura di servizi legali. Di conseguenza, tutte le informazioni ricevute saranno trattate conformemente alle leggi della Repubblica di Panama, in particolare ai sensi della Legge 81 del 2019 sulla Protezione dei Dati Personali e del Decreto Esecutivo 285 del 2021.",
      "Le informazioni fornite tramite moduli, e-mail, comunicazioni digitali o qualsiasi altro metodo di contatto possono includere dati personali, aziendali, finanziari, patrimoniali o di identificazione documentale. L'utente dichiara e garantisce che tutte le informazioni fornite sono veritiere, complete, aggiornate e legalmente fornite, assumendosi la piena responsabilità per qualsiasi falsità, omissione o inesattezza.",
      "L'invio di informazioni tramite questo sito web non costituirà in nessun caso la creazione automatica di un rapporto avvocato-cliente, mandato, rappresentanza legale o rapporto professionale di alcun tipo. Qualsiasi rapporto professionale richiederà l'accettazione espressa, formale e verificabile dello studio, nonché la formale sottoscrizione degli strumenti legali corrispondenti. Il mero ricevimento di una richiesta, comunicazione o documentazione non crea alcun obbligo di rispondere, accettare un incarico o assumere rappresentanza.",
      "Lo studio non garantisce risultati specifici, risoluzioni favorevoli, benefici economici, autorizzazioni amministrative, decisioni giudiziarie, approvazioni regolamentari o qualsiasi risultato concreto derivante dalla prestazione di servizi professionali. L'utente riconosce che qualsiasi decisione presa sulla base delle informazioni contenute in questo sito sarà intrapresa a sua esclusiva responsabilità. Lo studio adotta misure tecniche, amministrative e organizzative ragionevoli per proteggere le informazioni ricevute.",
      "Tutte le informazioni ricevute possono essere soggette a processi interni di due diligence, validazione documentale, verifica dell'identità, analisi della legittimità patrimoniale, origine dei fondi e conformità normativa. Il rifiuto di cooperare con questi processi può costituire motivo sufficiente per rifiutare o terminare qualsiasi rapporto professionale.",
      "Lo studio si riserva espressamente il diritto di astenersi dal fornire servizi professionali, sospendere azioni legali o risolvere rapporti contrattuali laddove vi siano ragionevoli indizi che i suoi servizi possano essere utilizzati per attività illecite, riciclaggio di denaro, frode, evasione fiscale illecita, simulazione legale fraudolenta, occultamento improprio di beni, corruzione o qualsiasi attività contraria alla legge nazionale o internazionale.",
      "L'utente dichiara espressamente che non utilizzerà i servizi legali dello studio per scopi illeciti, fraudolenti o contrari all'ordine pubblico e si impegna ad agire conformemente alla legge e ai principi di buona fede, trasparenza e legalità.",
      "Le informazioni personali saranno conservate solo per il tempo necessario ad adempiere al loro scopo legittimo, soddisfare obblighi legali, contrattuali o normativi, o esercitare e difendere diritti e interessi legittimi. Successivamente, tali informazioni potranno essere cancellate, bloccate o anonimizzate conformemente alla legge applicabile.",
      "Gli utenti possono esercitare i loro diritti di accesso, rettifica, aggiornamento, cancellazione o opposizione riguardo ai loro dati personali. Questo sito web può utilizzare cookie e tecnologie simili per scopi funzionali, statistici, di sicurezza e di ottimizzazione dell'esperienza di navigazione. Lo studio può modificare questa politica in qualsiasi momento. Qualsiasi rapporto legale derivante dall'uso di questo sito sarà disciplinato dalle leggi della Repubblica di Panama.",
    ],
    ctaTitle: "La tua privacy",
    ctaTitleHighlight: "è garantita.",
    ctaDesc: "Ogni interazione con Yanguéz Legal Group è condotta sotto rigorosi protocolli di riservatezza. Vi invitiamo a contattarci con totale tranquillità.",
    ctaBtn: "Contattaci in Modo Sicuro",
  },

  fr: {
    back: "Retour",
    subtitle: "Politique Juridique",
    title: "Politique de Confidentialité",
    titleHighlight: "et Conditions d'Utilisation",
    paragraphs: [
      "La présente Politique de Confidentialité et Conditions d'Utilisation régissent l'accès, la navigation et l'utilisation de ce site web, ainsi que le traitement des informations et données personnelles fournies par les utilisateurs, clients potentiels, clients et tiers interagissant avec nos services numériques ou professionnels. L'accès, l'utilisation ou la communication via ce site web constitue l'acceptation libre, expresse et éclairée des dispositions qui y sont contenues.",
      "Notre cabinet reconnaît le droit à la vie privée, à la confidentialité et à la protection des données personnelles comme des principes essentiels dans l'exercice professionnel du droit et dans la fourniture de services juridiques. En conséquence, toutes les informations reçues seront traitées conformément aux lois de la République du Panama, notamment en vertu de la Loi 81 de 2019 sur la Protection des Données Personnelles et du Décret Exécutif 285 de 2021.",
      "Les informations fournies via des formulaires, courriels, communications numériques ou tout autre moyen de contact peuvent inclure des données personnelles, corporatives, financières, patrimoniales ou d'identification documentaire. L'utilisateur déclare et garantit que toutes les informations fournies sont véridiques, complètes, mises à jour et légalement fournies, assumant l'entière responsabilité de toute fausseté, omission ou inexactitude.",
      "La transmission d'informations via ce site web ne constituera en aucun cas la création automatique d'une relation avocat-client, d'un mandat, d'une représentation légale ou d'une relation professionnelle quelconque. Toute relation professionnelle nécessitera l'acceptation expresse, formelle et vérifiable du cabinet, ainsi que l'exécution formelle des instruments juridiques correspondants. Le cabinet se réserve le droit absolu et discrétionnaire d'accepter, rejeter, suspendre ou mettre fin à toute consultation, processus d'évaluation ou relation professionnelle.",
      "Le cabinet ne garantit pas de résultats spécifiques, de résolutions favorables, de bénéfices économiques, d'autorisations administratives, de décisions judiciaires ou d'approbations réglementaires. L'utilisateur reconnaît que toute décision prise sur la base des informations contenues sur ce site sera entreprise à sa seule responsabilité. Le cabinet met en œuvre des mesures techniques, administratives et organisationnelles raisonnables pour protéger les informations reçues.",
      "Toutes les informations reçues peuvent être soumises à des processus internes de diligence raisonnable, de validation documentaire, de vérification d'identité, d'analyse de légitimité patrimoniale, d'origine des fonds et de conformité réglementaire. Le refus de coopérer avec ces processus peut constituer un motif suffisant pour rejeter ou mettre fin à toute relation professionnelle.",
      "Le cabinet se réserve expressément le droit de s'abstenir de fournir des services professionnels, de suspendre des actions juridiques ou de mettre fin à des relations contractuelles lorsqu'il existe des indications raisonnables que ses services pourraient être utilisés pour des activités illicites, du blanchiment d'argent, de la fraude, de l'évasion fiscale illicite, de la simulation légale frauduleuse, de la corruption ou toute activité contraire à la loi nationale ou internationale.",
      "L'utilisateur déclare expressément qu'il n'utilisera pas les services juridiques du cabinet à des fins illicites, frauduleuses ou contraires à l'ordre public et s'engage à agir conformément à la loi et aux principes de bonne foi, de transparence et de légalité.",
      "Les informations personnelles seront conservées uniquement le temps nécessaire pour remplir leur finalité légitime, respecter les obligations légales, contractuelles ou réglementaires, ou exercer et défendre des droits et intérêts légitimes. Ensuite, ces informations pourront être supprimées, bloquées ou anonymisées conformément à la loi applicable.",
      "Les utilisateurs peuvent exercer leurs droits d'accès, de rectification, de mise à jour, d'annulation ou d'opposition concernant leurs données personnelles. Ce site web peut utiliser des cookies et des technologies similaires à des fins fonctionnelles, statistiques et de sécurité. Le cabinet peut modifier cette politique à tout moment. Toute relation juridique découlant de l'utilisation de ce site sera régie par les lois de la République du Panama, et tout litige sera soumis exclusivement aux tribunaux compétents de la République du Panama.",
    ],
    ctaTitle: "Votre vie privée",
    ctaTitleHighlight: "est garantie.",
    ctaDesc: "Chaque interaction avec Yanguéz Legal Group est menée sous des protocoles de confidentialité stricts. Nous vous invitons à nous contacter en toute sérénité.",
    ctaBtn: "Contactez-nous en Toute Sécurité",
  },

  pt: {
    back: "Voltar",
    subtitle: "Política Jurídica",
    title: "Política de Privacidade",
    titleHighlight: "e Termos de Uso",
    paragraphs: [
      "A presente Política de Privacidade e Termos de Uso regem o acesso, a navegação e o uso deste website, bem como o tratamento das informações e dados pessoais fornecidos por usuários, clientes em potencial, clientes e terceiros que interajam com nossos serviços digitais ou profissionais. O acesso, uso ou comunicação por meio deste website constitui a aceitação livre, expressa e informada das disposições aqui contidas.",
      "Nosso escritório reconhece o direito à privacidade, confidencialidade e proteção de dados pessoais como princípios essenciais no exercício profissional do direito e na prestação de serviços jurídicos. Consequentemente, todas as informações recebidas serão tratadas em conformidade com as leis da República do Panamá, especialmente no âmbito da Lei 81 de 2019 sobre Proteção de Dados Pessoais e do Decreto Executivo 285 de 2021.",
      "As informações fornecidas por meio de formulários, e-mails, comunicações digitais ou qualquer outro método de contato podem incluir dados pessoais, corporativos, financeiros, patrimoniais ou de identificação documental. O usuário declara e garante que todas as informações fornecidas são verdadeiras, completas, atualizadas e legalmente fornecidas, assumindo total responsabilidade por qualquer falsidade, omissão ou imprecisão.",
      "O envio de informações por meio deste website não constituirá em nenhuma circunstância a criação automática de uma relação advogado-cliente, mandato, representação legal ou relação profissional de qualquer tipo. Qualquer relação profissional exigirá a aceitação expressa, formal e verificável do escritório, bem como a execução formal dos instrumentos legais correspondentes. O escritório reserva-se o direito absoluto e discricionário de aceitar, rejeitar, suspender ou encerrar qualquer consulta, processo de avaliação ou relação profissional.",
      "O escritório não garante resultados específicos, resoluções favoráveis, benefícios econômicos, autorizações administrativas, decisões judiciais, aprovações regulatórias ou qualquer resultado concreto decorrente da prestação de serviços profissionais. O usuário reconhece que qualquer decisão tomada com base nas informações contidas neste site será tomada sob sua exclusiva responsabilidade. O escritório implementa medidas técnicas, administrativas e organizacionais razoáveis para proteger as informações recebidas.",
      "Todas as informações recebidas podem ser submetidas a processos internos de due diligence, validação documental, verificação de identidade, análise de legitimidade patrimonial, origem de fundos e conformidade regulatória. A recusa em cooperar com esses processos pode constituir motivo suficiente para rejeitar ou encerrar qualquer relação profissional.",
      "O escritório reserva-se expressamente o direito de abster-se de prestar serviços profissionais, suspender ações legais ou encerrar relações contratuais quando houver indícios razoáveis de que seus serviços possam ser utilizados para atividades ilícitas, lavagem de dinheiro, fraude, evasão fiscal ilícita, simulação legal fraudulenta, ocultação indevida de bens, corrupção ou qualquer atividade contrária à legislação nacional ou internacional.",
      "O usuário declara expressamente que não utilizará os serviços jurídicos do escritório para fins ilícitos, fraudulentos ou contrários à ordem pública e compromete-se a agir de acordo com a lei e sob os princípios da boa-fé, transparência e legalidade.",
      "As informações pessoais serão retidas apenas pelo tempo necessário para cumprir sua finalidade legítima, cumprir obrigações legais, contratuais ou regulatórias, ou exercer e defender direitos e interesses legítimos. Após esse período, tais informações poderão ser excluídas, bloqueadas ou anonimizadas de acordo com a lei aplicável.",
      "Os usuários podem exercer seus direitos de acesso, retificação, atualização, cancelamento ou oposição em relação aos seus dados pessoais. Este website pode utilizar cookies e tecnologias similares para fins funcionais, estatísticos e de segurança. O escritório pode modificar esta política a qualquer momento. Qualquer relação jurídica decorrente do uso deste website será regida pelas leis da República do Panamá, e qualquer controvérsia será submetida exclusivamente aos tribunais competentes da República do Panamá.",
    ],
    ctaTitle: "Sua privacidade",
    ctaTitleHighlight: "é garantida.",
    ctaDesc: "Cada interação com o Yanguéz Legal Group é conduzida sob rigorosos protocolos de confidencialidade. Convidamos você a entrar em contato com total tranquilidade.",
    ctaBtn: "Fale Conosco com Segurança",
  },
};
