export type Language = 'en' | 'es' | 'it' | 'fr' | 'pt';

export const translations = {
  en: {
    header: { home: "Home", services: "Services", about: "About", contact: "Contact", consultation: "CONSULTATION" },
    hero: { tagline: "Trusted Counsel. Proven Results.", title: "Full-Service Law Firm", titleHighlight: "in Panama", description: "Strategic legal services in Panama for businesses, investors, and international clients.", primaryCTA: "SECURE YOUR LEGACY", secondaryCTA: "PRIVATE CONSULTATION" },
    footer: { description: "Sophisticated legal council specializing in strategic asset protection and international business structures in the Republic of Panama.", jurisdiction: "Jurisdiction", lawFirm: "Law Firm", panamaCorps: "Panama Corporations", privateFoundations: "Private Interest Foundations", vesselReg: "Vessel Registration", immigration: "Immigration Services", ourProcess: "Our Process", expertise: "Expertise" },
    about: { subtitle: "Our Legacy", title: "Elite Counsel for", titleHighlight: "Global Visionaries", p1: "Yanguéz Legal Group was founded on the principles of absolute discretion, strategic innovation, and unwavering loyalty to our clients' interests.", p2: "Based in the heart of Panama City's financial district, we have evolved into a premier destination for international asset protection, serving as a trusted bridge between global wealth and Panamanian legal stability.", exclusivityTitle: "Exclusivity", exclusivityDesc: "We work with an exclusive client portfolio to ensure first-class service.", precisionTitle: "Precision", precisionDesc: "Meticulous attention to every legal detail.", imageTrust: "Trust.", imageDesc: "We build solid legal solutions focused on asset protection, strategic asset organization, and the preservation of high-value interests, with a long-term legal and structural vision." },
    whyUs: { subtitle: "Strategic Advantage", title: "Why", titleHighlight: "Panama?", description: "Discover why the world's most sophisticated investors choose Panama as their primary jurisdiction for asset protection.", reason1Title: "Territorial Taxation", reason1Desc: "Panama only taxes income generated within its borders, making it an ideal hub for international wealth management.", reason2Title: "Legal Stability", reason2Desc: "A robust legal system based on civil law with strong constitutional protections for private property and foreign investment.", reason3Title: "Confidentiality", reason3Desc: "World-class privacy standards designed to protect your sensitive financial and personal information from unauthorized access." },
    contact: { subtitle: "Confidential", title: "Start the", titleHighlight: "Conversation", description: "Your privacy is our priority. Reach out to our senior partners through secure channels for a consultation.", emailTitle: "Email", officeTitle: "Office", whatsappTitle: "WhatsApp", whatsappSubtitle: "Direct Partner Line", formName: "Name", formPhone: "Phone (Optional)", formEmail: "Email", formSubject: "Subject of Consultation", formMessage: "Message", formNamePlaceholder: "Enter your name", formPhonePlaceholder: "Enter your phone number", formEmailPlaceholder: "Enter your email", formMessagePlaceholder: "How can we assist you?", submitIdle: "REQUEST CONSULTATION", submitLoading: "SENDING...", submitSuccess: "MESSAGE SENT", option1: "Incorporation of a Company in Panama", option2: "Immigration Services", option3: "Corporate Governance", option4: "Other Services" },
    process: { methodology: "Methodology", title: "The", titleHighlight: "Process", titleEnd: "of Excellence", description: "We provide legal services aimed at delivering legal certainty, structure, and support in corporate, asset-related, and litigation matters.", step1Title: "Analysis", step1Desc: "We assess each matter with legal judgment and strategic vision to identify risks, opportunities, and the most effective course of action.", step2Title: "Design", step2Desc: "We create legal solutions with a strategic approach, aimed at maximizing protection, efficiency, and legal control.", step3Title: "Execution", step3Desc: "We implement and manage each process with precision, efficiency, and comprehensive guidance through to its proper conclusion.", expertise: "Expertise", servicesTitle: "Services", viewDetails: "View Details" },
    forms: { back: "Back", specializedService: "Specialized Service", contactExpert: "CONTACT AN EXPERT" }
  },
  es: {
    header: { home: "Inicio", services: "Servicios", about: "Nosotros", contact: "Contacto", consultation: "CONSULTA" },
    hero: { tagline: "Asesoría de Confianza. Resultados Comprobados.", title: "Bufete de Servicio Completo", titleHighlight: "en Panamá", description: "Servicios legales estratégicos en Panamá para empresas, inversionistas y clientes internacionales.", primaryCTA: "ASEGURE SU LEGADO", secondaryCTA: "CONSULTA PRIVADA" },
    footer: { description: "Asesoría legal sofisticada especializada en protección estratégica de activos y estructuras de negocios internacionales en la República de Panamá.", jurisdiction: "Jurisdicción", lawFirm: "Firma Legal", panamaCorps: "Corporaciones Panameñas", privateFoundations: "Fundaciones de Interés Privado", vesselReg: "Registro de Naves", immigration: "Servicios Migratorios", ourProcess: "Nuestro Proceso", expertise: "Experiencia" },
    about: { subtitle: "Nuestro Legado", title: "Asesoría de Élite para", titleHighlight: "Visionarios Globales", p1: "Yanguéz Legal Group se fundó sobre los principios de discreción absoluta, innovación estratégica y lealtad inquebrantable a los intereses de nuestros clientes.", p2: "Ubicados en el corazón del distrito financiero de la Ciudad de Panamá, hemos evolucionado hasta convertirnos en el principal destino para la protección internacional de activos.", exclusivityTitle: "Exclusividad", exclusivityDesc: "Trabajamos con una cartera de clientes exclusiva para garantizar un servicio de primer nivel.", precisionTitle: "Precisión", precisionDesc: "Atención meticulosa a cada detalle legal.", imageTrust: "Confianza.", imageDesc: "Construimos soluciones legales sólidas enfocadas en la protección de activos con una visión a largo plazo." },
    whyUs: { subtitle: "Ventaja Estratégica", title: "¿Por qué", titleHighlight: "Panamá?", description: "Descubra por qué los inversores más sofisticados eligen Panamá como su jurisdicción principal para la protección de activos.", reason1Title: "Tributación Territorial", reason1Desc: "Panamá solo grava los ingresos generados dentro de sus fronteras.", reason2Title: "Estabilidad Legal", reason2Desc: "Un sistema legal robusto basado en el derecho civil con fuertes protecciones constitucionales.", reason3Title: "Confidencialidad", reason3Desc: "Estándares de privacidad de clase mundial diseñados para proteger su información financiera." },
    contact: { subtitle: "Confidencial", title: "Inicie la", titleHighlight: "Conversación", description: "Su privacidad es nuestra prioridad. Contáctenos a través de canales seguros para una consulta.", emailTitle: "Correo", officeTitle: "Oficina", whatsappTitle: "WhatsApp", whatsappSubtitle: "Línea Directa", formName: "Nombre", formPhone: "Contacto (No obligatorio)", formEmail: "Correo", formSubject: "Asunto", formMessage: "Mensaje", formNamePlaceholder: "Ingrese su nombre", formPhonePlaceholder: "Ingrese su número de contacto", formEmailPlaceholder: "Ingrese su correo", formMessagePlaceholder: "¿Cómo podemos asistirle?", submitIdle: "SOLICITAR CONSULTA", submitLoading: "ENVIANDO...", submitSuccess: "MENSAJE ENVIADO", option1: "Incorporación de Sociedad en Panamá", option2: "Servicios Migratorios", option3: "Gobierno Corporativo", option4: "Otros Servicios" },
    process: { methodology: "Metodología", title: "El", titleHighlight: "Proceso", titleEnd: "de Excelencia", description: "Proveemos servicios orientados a brindar seguridad jurídica, estructura y respaldo.", step1Title: "Análisis", step1Desc: "Evaluamos cada asunto con criterio legal y visión estratégica.", step2Title: "Diseño", step2Desc: "Creamos soluciones legales con enfoque estratégico.", step3Title: "Ejecución", step3Desc: "Implementamos y gestionamos cada proceso con precisión.", expertise: "Experiencia", servicesTitle: "Servicios", viewDetails: "Ver Detalles" },
    forms: { back: "Volver", specializedService: "Servicio Especializado", contactExpert: "CONTACTAR A UN EXPERTO" }
  },
  it: {
    header: { home: "Home", services: "Servizi", about: "Chi Siamo", contact: "Contatti", consultation: "CONSULENZA" },
    hero: { tagline: "Consulenza di Fiducia. Risultati Comprovati.", title: "Studio Legale a Servizio Completo", titleHighlight: "a Panama", description: "Servizi legali strategici a Panama per aziende, investitori e clienti internazionali.", primaryCTA: "ASSICURA LA TUA EREDITÀ", secondaryCTA: "CONSULENZA PRIVATA" },
    footer: { description: "Consulenza legale sofisticata specializzata in protezione strategica degli asset a Panama.", jurisdiction: "Giurisdizione", lawFirm: "Studio Legale", panamaCorps: "Società Panamensi", privateFoundations: "Fondazioni Private", vesselReg: "Registrazione Navale", immigration: "Immigrazione", ourProcess: "Il Nostro Processo", expertise: "Esperienza" },
    about: { subtitle: "La Nostra Eredità", title: "Consulenza d'Élite per", titleHighlight: "Visionari Globali", p1: "Yanguéz Legal Group è stato fondato sui principi di assoluta discrezione e innovazione.", p2: "Siamo una destinazione principale per la protezione internazionale del patrimonio.", exclusivityTitle: "Esclusività", exclusivityDesc: "Lavoriamo con un portafoglio clienti esclusivo.", precisionTitle: "Precisione", precisionDesc: "Attenzione meticolosa a ogni dettaglio legale.", imageTrust: "Fiducia.", imageDesc: "Costruiamo solide soluzioni legali incentrate sulla protezione patrimoniale." },
    whyUs: { subtitle: "Vantaggio Strategico", title: "Perché", titleHighlight: "Panama?", description: "Scopri perché gli investitori scelgono Panama per la protezione del patrimonio.", reason1Title: "Tassazione Territoriale", reason1Desc: "Panama tassa solo i redditi generati all'interno dei suoi confini.", reason2Title: "Stabilità Legale", reason2Desc: "Un robusto sistema legale basato sul diritto civile.", reason3Title: "Riservatezza", reason3Desc: "Standard di privacy di livello mondiale." },
    contact: { subtitle: "Riservato", title: "Inizia la", titleHighlight: "Conversazione", description: "La tua privacy è la nostra priorità. Contattaci per una consulenza.", emailTitle: "Email", officeTitle: "Ufficio", whatsappTitle: "WhatsApp", whatsappSubtitle: "Linea Diretta", formName: "Nome", formPhone: "Contatto (Opzionale)", formEmail: "Email", formSubject: "Oggetto", formMessage: "Messaggio", formNamePlaceholder: "Inserisci il tuo nome", formPhonePlaceholder: "Inserisci il tuo numero", formEmailPlaceholder: "Inserisci la tua email", formMessagePlaceholder: "Come possiamo aiutarti?", submitIdle: "RICHIEDI CONSULENZA", submitLoading: "INVIO IN CORSO...", submitSuccess: "MESSAGGIO INVIATO", option1: "Costituzione di Società a Panama", option2: "Servizi di Immigrazione", option3: "Governance Aziendale", option4: "Altri Servizi" },
    process: { methodology: "Metodologia", title: "Il", titleHighlight: "Processo", titleEnd: "di Eccellenza", description: "Forniamo servizi legali mirati a garantire certezza del diritto e struttura.", step1Title: "Analisi", step1Desc: "Valutiamo ogni questione con giudizio legale e visione strategica.", step2Title: "Design", step2Desc: "Creiamo soluzioni legali con un approccio strategico.", step3Title: "Esecuzione", step3Desc: "Implementiamo e gestiamo ogni processo con precisione.", expertise: "Esperienza", servicesTitle: "Servizi", viewDetails: "Vedi Dettagli" },
    forms: { back: "Indietro", specializedService: "Servizio Specializzato", contactExpert: "CONTATTA UN ESPERTO" }
  },
  fr: {
    header: { home: "Accueil", services: "Services", about: "À Propos", contact: "Contact", consultation: "CONSULTATION" },
    hero: { tagline: "Conseils de Confiance. Résultats Prouvés.", title: "Cabinet d'Avocats à Service Complet", titleHighlight: "à Panama", description: "Services juridiques stratégiques à Panama pour les entreprises, les investisseurs et les clients internationaux.", primaryCTA: "SÉCURISEZ VOTRE HÉRITAGE", secondaryCTA: "CONSULTATION PRIVÉE" },
    footer: { description: "Conseils juridiques sophistiqués spécialisés dans la protection stratégique des actifs au Panama.", jurisdiction: "Juridiction", lawFirm: "Cabinet d'Avocats", panamaCorps: "Sociétés Panaméennes", privateFoundations: "Fondations Privées", vesselReg: "Enregistrement Navires", immigration: "Immigration", ourProcess: "Notre Processus", expertise: "Expertise" },
    about: { subtitle: "Notre Héritage", title: "Conseils d'Élite pour", titleHighlight: "Visionnaires", p1: "Yanguéz Legal Group a été fondé sur les principes de la discrétion absolue.", p2: "Nous sommes une destination de choix pour la protection internationale des actifs.", exclusivityTitle: "Exclusivité", exclusivityDesc: "Un portefeuille de clients exclusif.", precisionTitle: "Précision", precisionDesc: "Attention méticuleuse à chaque détail juridique.", imageTrust: "Confiance.", imageDesc: "Nous construisons des solutions juridiques solides." },
    whyUs: { subtitle: "Avantage Stratégique", title: "Pourquoi le", titleHighlight: "Panama ?", description: "Découvrez pourquoi les investisseurs choisissent le Panama.", reason1Title: "Fiscalité Territoriale", reason1Desc: "Le Panama n'impose que les revenus générés à l'intérieur de ses frontières.", reason2Title: "Stabilité Juridique", reason2Desc: "Un système juridique robuste basé sur le droit civil.", reason3Title: "Confidentialité", reason3Desc: "Des normes de confidentialité de classe mondiale." },
    contact: { subtitle: "Confidentiel", title: "Commencez la", titleHighlight: "Conversation", description: "Votre vie privée est notre priorité.", emailTitle: "Email", officeTitle: "Bureau", whatsappTitle: "WhatsApp", whatsappSubtitle: "Ligne Directe", formName: "Nom", formPhone: "Contact (Optionnel)", formEmail: "Email", formSubject: "Sujet", formMessage: "Message", formNamePlaceholder: "Votre nom", formPhonePlaceholder: "Votre numéro", formEmailPlaceholder: "Votre email", formMessagePlaceholder: "Comment pouvons-nous vous aider ?", submitIdle: "DEMANDER UNE CONSULTATION", submitLoading: "ENVOI EN COURS...", submitSuccess: "MESSAGE ENVOYÉ", option1: "Constitution de Société au Panama", option2: "Services d'Immigration", option3: "Gouvernance d'Entreprise", option4: "Autres Services" },
    process: { methodology: "Méthodologie", title: "Le", titleHighlight: "Processus", titleEnd: "d'Excellence", description: "Nous fournissons des services juridiques visant à offrir une sécurité juridique.", step1Title: "Analyse", step1Desc: "Nous évaluons chaque question avec un jugement juridique.", step2Title: "Conception", step2Desc: "Nous créons des solutions juridiques avec une approche stratégique.", step3Title: "Exécution", step3Desc: "Nous mettons en œuvre et gérons chaque processus avec précision.", expertise: "Expertise", servicesTitle: "Services", viewDetails: "Voir les Détails" },
    forms: { back: "Retour", specializedService: "Service Spécialisé", contactExpert: "CONTACTER UN EXPERT" }
  },
  pt: {
    header: { home: "Início", services: "Serviços", about: "Sobre", contact: "Contato", consultation: "CONSULTA" },
    hero: { tagline: "Consultoria de Confiança. Resultados Comprovados.", title: "Escritório de Advocacia de Serviço Completo", titleHighlight: "no Panamá", description: "Serviços jurídicos estratégicos no Panamá para empresas, investidores e clientes internacionais.", primaryCTA: "GARANTA SEU LEGADO", secondaryCTA: "CONSULTA PRIVADA" },
    footer: { description: "Assessoria jurídica sofisticada especializada em proteção de ativos no Panamá.", jurisdiction: "Jurisdição", lawFirm: "Escritório", panamaCorps: "Corporações Panamenhas", privateFoundations: "Fundações Privadas", vesselReg: "Registro de Embarcações", immigration: "Imigração", ourProcess: "Nosso Processo", expertise: "Experiência" },
    about: { subtitle: "Nosso Legado", title: "Assessoria de Elite para", titleHighlight: "Visionários", p1: "Yanguéz Legal Group foi fundado sob princípios de discrição absoluta.", p2: "Somos o principal destino para proteção internacional de ativos.", exclusivityTitle: "Exclusividade", exclusivityDesc: "Trabalhamos com uma carteira de clientes exclusiva.", precisionTitle: "Precisão", precisionDesc: "Atenção meticulosa a cada detalhe legal.", imageTrust: "Confiança.", imageDesc: "Construímos soluções jurídicas sólidas focadas na proteção de ativos." },
    whyUs: { subtitle: "Vantagem Estratégica", title: "Por que o", titleHighlight: "Panamá?", description: "Descubra por que os investidores escolhem o Panamá.", reason1Title: "Tributação Territorial", reason1Desc: "O Panamá tributa apenas a renda gerada dentro de suas fronteiras.", reason2Title: "Estabilidade Jurídica", reason2Desc: "Um sistema jurídico robusto baseado no direito civil.", reason3Title: "Confidencialidade", reason3Desc: "Padrões de privacidade de classe mundial." },
    contact: { subtitle: "Confidencial", title: "Inicie a", titleHighlight: "Conversa", description: "Sua privacidade é nossa prioridade.", emailTitle: "E-mail", officeTitle: "Escritório", whatsappTitle: "WhatsApp", whatsappSubtitle: "Linha Direta", formName: "Nome", formPhone: "Contato (Opcional)", formEmail: "E-mail", formSubject: "Assunto", formMessage: "Mensagem", formNamePlaceholder: "Seu nome", formPhonePlaceholder: "Seu número", formEmailPlaceholder: "Seu e-mail", formMessagePlaceholder: "Como podemos ajudar?", submitIdle: "SOLICITAR CONSULTA", submitLoading: "ENVIANDO...", submitSuccess: "MENSAGEM ENVIADA", option1: "Constituição de Empresa no Panamá", option2: "Serviços de Imigração", option3: "Governança Corporativa", option4: "Outros Serviços" },
    process: { methodology: "Metodologia", title: "O", titleHighlight: "Processo", titleEnd: "de Excelência", description: "Fornecemos serviços jurídicos visando segurança jurídica.", step1Title: "Análise", step1Desc: "Avaliamos cada questão com visão estratégica.", step2Title: "Design", step2Desc: "Criamos soluções jurídicas com uma abordagem estratégica.", step3Title: "Execução", step3Desc: "Implementamos e gerenciamos cada processo com precisão.", expertise: "Experiência", servicesTitle: "Serviços", viewDetails: "Ver Detalhes" },
    forms: { back: "Voltar", specializedService: "Serviço Especializado", contactExpert: "CONTATAR UM ESPECIALISTA" }
  }
};
